---
title: "First Knit"
author: "Nicole Anderson"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct punctuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare English class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
Due to me growing up in Germany I never attended Highschool. The German school system is very different from the US system. I was able to graduate after 9th grade to attend trade school. If I have to choose, I will say English is easier than math. But my decision is solely because I am really bad at math. I'm not good at either one of the subjects given to choose from. My spelling is all over the place and I have taught myself to keep up with the English language since the age of 11. So, I would say I'm work in progress.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I own a windows computer that I hardly ever use. For that reason, I would rate myself a 2 on the 1 to 10 scale. Even though I try to figure things out regarding computers and their usage it's still a very frustrating experience. The internet connection is very good if they are not shutting it down for odd reasons without any notification.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer to be called Nicole. Some of my Co-workers call me Nic and that's just as good as Nicole.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I would love to raise my children to be happy, kind, and loving adults that have a sense of humor to brighten someone’s day. Furthermore, I hope to give them the tools to overcome any obstacle that life throws at them. For myself I am trying to create a fulfilling career change after turning my back on teaching. My subjects are set due to me choosing to go into nursing. Once I am done becoming a nurse I would love study psychology, just for fun. I'm trying to achieve a BSN in Nursing.  
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have lived in a foreign country for over 30 years. Germany is a beautiful small country in Europe. Besides of living in Germany I have gone to England, Italy, the Netherlands, France, Ireland, Switzerland, and Austria. My father served in the Army for over 20 years, but I've never joined the Military. My experience is the experience of a dependent. 
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
I am taking Statistics because I must, in order to apply for the LVN to RN bridge Program. The higher the grade the better it would be. My plan is to work hard and hope for the best.  
   
 






  




